apps/tienda/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from apps.tienda.views import (
    HomeView,
    ItemsListView,
    ItemDetailView,
    UserProfileView,
    OrderSumaryView,
    CheckoutView,
    ContactView,
    AboutView,
    add_to_cart,
    addto,
    update_size,
    remove_single_item_from_cart,
    remove_from_cart,
    WebpayConfirm,
    pdfFactura
)
app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('product-list/', ItemsListView.as_view(), name='list-product'),
    path('product/<slug>', ItemDetailView.as_view(), name='product'),
    path('user/<pk>', UserProfileView.as_view(), name='user'),
    path('cart/', OrderSumaryView.as_view(), name='order-sumary'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('about/', AboutView.as_view(), name='about-us'),
    path('add-to-cart/<slug>/<talla>/', add_to_cart, name='add-to-cart'),
    path('addto/', addto, name='addto'),
    path('update-size/', addto, name='update-size'),
    path('confirm/', WebpayConfirm, name='confirm'),
    path('pdf-fact/<pk>/', pdfFactura, name='fact'),
    path('remove-from-cart/<slug>/<talla>/', remove_from_cart, name='remove-from-cart'),
    path('remove-single-from-cart/<slug>/<talla>/', remove_single_item_from_cart, name='remove-single-item-from-cart'),

]

# URLS DE VISTAS IMPLICITAS
urlpatterns += [
    path('index-product-list/', TemplateView.as_view(
                                    template_name='shop.html'
                                    ), 
                                    name='index-list-product'),
]

ecommerce/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from allauth.socialaccount.models import SocialToken, SocialAccount, SocialApp
from django.contrib import admin

admin.site.site_header = "Administrador de Llona"
admin.site.site_title = "Administración De Llona"

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('apps.tienda.urls', namespace='core')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.unregister(SocialToken)
admin.site.unregister(SocialAccount)
admin.site.unregister(SocialApp)

templates/check-out.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Bienvenido a llona
{% endblock %}
{% load static%}
{% block content %}
    

    <!-- Breadcrumb Section Begin -->
    <div class="breacrumb-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb-text product-more">
                        <a href="{% url 'core:home' %}"><i class="fa fa-home"></i> Home</a>
                        <a href="{% url 'core:list-product' %}">Tienda</a>
                        <span>Finalizar Compra</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb Section Begin -->
    <!-- Shopping Cart Section Begin -->
    <section class="checkout-section spad">
        <div class="container">
            <form action="{% url 'core:checkout' %}" class="checkout-form" method="POST">
                {% csrf_token %}
                <div class="row">
                    <div class="col-lg-6">
                        <h4>Detalles de Facturación</h4>
                            <div class="row">
                                <div class="col-lg-12 form-noPost">
                                    <label for="nombre">Nombre:<span></span></label>
                                    <input type="text" name="nombre" disabled value="{{user.first_name}}">
                                    <label for="nombre">Apellido:<span></span></label>
                                    <input type="text" disabled value="{{user.last_name}}">
                                    <label for="nombre">Teléfono:<span></span></label>
                                    <input type="text" disabled value="{{user.phone}}">
                                    <label for="nombre" id="rut">RUT:<span></span></label>
                                    <input type="text" disabled value="{{user.rut}}">
                                </div>
                            </div>
                            <div class="col-md-12">
                                Selecciona tu tipo de entrega
                                <select id="select" class="form-control form-control-lg" name="select">
                                    <option value="retiro">Retiro en tienda.</option>
                                    <option value="starken">Envio por Starken (Por pagar).</option>
                                    <option value="delivery">Delivery (Santiago).</option>
                                </select>
                            </div>
                            <br>
                            <div class="col-md-12" id="direccion-tienda" style="display: block;">
                                Dirección de entrega Alcalde Pedro Alarcon 875. San miguel.
                            </div>
                            <br>
                            <div class="col-md-12" style="display: none;" id="comunas">
                                Comunas con delivery disponible:
                                <select class="form-control form-control-lg" id="selectComuna" name="comuna">
                                    <option value="">Seleccione un delivery</option>
                                </select>
                            <br>
                            </div>
                            <div class="row" id="form-direct" style="display: none;">
                                <div class="col-lg-12">
                                    <label for="street_address">Dirección exacta:<span>*</span></label>
                                    {{form.street_address}}
                                </div>
                                <div class="col-lg-12">
                                    <label for="street">Departamento / Casa / Oficina<span>*</span></label>
                                    {{form.apartment_address}}
                                </div>
                                <div class="col-lg-12" id="Comunas" style="display: none;">
                                    <label for="comunasS">Comuna:</label>
                                    <input type="text" class="street-first" name="comunaStarken" id="comunasS" >
                                </div>
                                <div class="col-lg-12">
                                    <label for="zip">Déjanos un mensaje, quien lo recibirá o alguna referencia del sitio de entrega</label>
                                    {{form.description}}
                                </div>
                            </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="place-order">
                            <h4>Tú Orden</h4>
                            <div class="order-total">
                                <ul class="order-table">
                                    <li>Producto <span>Total</span></li>
                                    {% load humanize %}
                                    {% for order in order.items.all %}
                                        <li class="fw-normal">x{{ order.quantity }} {{ order.item.title }}<span>${{ order.totalItem|floatformat:"0"|intcomma }}</span></li>
                                    {% endfor %}
                                    <li class="fw-normal">Subtotal <span>${{ order.get_total|floatformat:"0"|intcomma }}</span></li>
                                    <input type="hidden" value="{{ order.get_total|floatformat:"0" }}" id="subtotal">
                                    <li class="total-price" id="deli-li" style="display: none;">Delivery <span id="deli"></span></li>
                                    <li class="total-price">Total <span id="total"></span></li>
                                    <input type="hidden" id="totalenv" name="mount">
                                </ul>
                                <div class="payment-check">
                                    {% for value, name in form.fields.payment_option.choices %}
                                    <div class="pc-item">
                                        <label for="{{name}}">
                                            {{name|title}}
                                            <input type="checkbox" id="{{name}}" value="{{value}}" name="payment_option">
                                            <span class="checkmark"></span>
                                        </label>
                                    </div>
                                    {% endfor %}
                                </div>
                                <!-- <input type="hidden" value="{{ order.get_total }}" > -->
                                <div class="order-btn">
                                    <button type="submit" class="site-btn place-btn">Finalizar Compra</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </section>
    <!-- Shopping Cart Section End -->
{% endblock %}

{% block extrajs %}
<script>
    var data = {{json|safe}}
</script>
<script src="{% static 'js/hidden.js' %}"></script>
{% endblock %}

templates/confirm.html
<!DOCTYPE html>
<html lang="zxx">
{% load cart_template_tags %}

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Fashi Template">
    <meta name="keywords" content="Fashi, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} {% endblock %}</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Muli:300,400,500,600,700,800,900&display=swap" rel="stylesheet">
    {% load static %}
    <!-- Css Styles -->

    <link rel="icon" href="{% static 'img/llonas.png' %}" type="image/png" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Header Section Begin -->
    <header class="header-section">
        <div class="header-top">
            <div class="container">
                <div class="ht-left">
                    <div class="mail-service">
                        <i class=" fa fa-envelope"></i>
                        inversionesllonapa@gmail.com
                    </div>
                    <div class="phone-service">
                        <i class=" fa fa-phone"></i>
                        +56 9 4980 6952
                    </div>
                </div>
                {% if user.is_authenticated %}
                <div class="ht-right">
                    <a href="{% url 'account_logout' %}" class="login-panel"><i class="fa fa-sign-out"></i>Salir</a>
                    <a href="{% url 'core:user' user.id %}" class="login-panel"><i
                            class="fa fa-user"></i>{{user.first_name}}</a>
                    <div class="top-social">
                        <a href="https://www.instagram.com/llona.cl" target="_blank"><i class="ti-instagram"></i></a>
                    </div>
                </div>
                {% else %}
                <div class="ht-right">
                    <a href="{% url 'account_signup' %}" class="login-panel"><i
                            class="fa fa-user-plus"></i>Registrate</a>
                    <a href="{% url 'account_login' %}" class="login-panel"><i class="fa fa-user"></i>Iniciar sesion</a>
                    <div class="top-social">
                        <a href="https://www.instagram.com/llona.cl" target="_blank"><i class="ti-instagram"></i></a>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
        <div class="container1">
            <div class="container">
                <div class="inner-header">
                    <div class="row">
                        <div class="col-lg-7 col-md-7">
                            <div class="logo text-right">
                                <p class="llona" style=" color: rgb(255, 255, 255);">Llona</p>
                            </div>
                        </div>
                        <br>
                        <!--<div class="col-lg-6 col-md-6">
                        <div class="advanced-search">
                            <button type="button" class="category-btn">¿Buscas algo?</button>
                            <div class="input-group">
                                <input type="text" placeholder="¿Qué necesitas?">
                                <button type="button"><i class="ti-search"></i></button>
                            </div>
                        </div>
                    </div>-->
                        {% if user.is_authenticated %}
                        <div class="col-lg-3 text-right col-md-3">
                            <ul class="nav-right">
                                <li class="cart-icon">
                                    <a href="{% url 'core:order-sumary' %}">
                                        <i class="icon_bag_alt"></i>
                                        <span>{{ request.user|cart_item_count }}</span>
                                    </a>
                                </li>
                                <li class="cart-price"></li>
                            </ul>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="nav-item">
                <div class="contenido">
                    <div class="nav-depart">
                        <div class="depart-btn">
                            <i class="ti-menu"></i>
                            <span>Departamentos</span>
                            <ul class="depart-hover">
                                <!--<li class="active"><a href="#">Ropa de mujer</a></li>-->
                                <li><a href="{% url 'core:list-product' %}">Ropa de hombre</a></li>
                            </ul>
                        </div>
                    </div>
                    <nav class="nav-menu mobile-menu">
                        <ul>
                            <li id="inicio"><a href="{% url 'core:home' %}">Inicio</a></li>
                            <li id="tienda"><a href="{% url 'core:list-product' %}">Tienda</a></li>
                            <li id="about"><a href="{% url 'core:about-us' %}">Quiénes somos</a></li>
                            <li id="contact"><a href="{% url 'core:contact' %}">Contáctanos</a></li>
                            <li id="detalles"><a href="#">Detalles</a>
                                <ul class="dropdown">
                                    <li><a href="{% url 'core:order-sumary' %}">Lista de<br> compras</a></li>
                                </ul>
                            </li>
                        </ul>
                        <li id="whatsapp"><a href="https://wa.me/message/B6YPR5OLNCDCH1" target="_blank">Whatsapp</a>
                    </nav>
                    <div id="mobile-menu-wrap"></div>
                </div>
            </div>
        </div>
    </header>
    <div class="container">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}

            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
        {% endif %}
    </div>
    <!-- Header End -->
    <div class="breacrumb-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb-text">
                        <a href="#"><i class="fa fa-home"></i> Inicio</a>
                        <a href="#"><i class="fa fa-home"></i> Tienda</a>
                        <a href="#"><i class="fa fa-home"></i> Finalizar Compra</a>
                        <span>Pagar</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>
    <div class="container">
        <div class="text-center">
            <h3>PAGO EXITOSO</h3>
            <a href="{% url 'core:list-product' %}" class="btn btn-success">Volver a la tienda</a>
            <br><br>
            <a href="{% url 'core:fact' pk=orden.pk %}" class="btn btn-success" target="_blank">Ver Orden de entrega</a>
            <br>
            Esta orden de entrega tambien se puede ver desde tu perfil de usuario
        </div>
    </div>
    <br>
    <!-- Footer Section Begin -->
    <footer class="footer-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                    <div class="footer-left">
                        <div class="footer-logo">
                            <a href="#"><img src="{% static 'img/llona1.png' %}" alt=""></a>
                        </div>
                        <ul>
                            <li>Dirección: San Miguel, Santiago</li>
                            <li>Telefono: +56 9 4980 6952</li>
                            <li>Email: inversionesllonapa@gmail.com</li>
                        </ul>
                        <div class="footer-social sss">
                            <a href="https://www.instagram.com/llona.cl/" target="_blank"><i
                                    class="fa fa-instagram"></i></a>
                            <a href="https://wa.me/message/B6YPR5OLNCDCH1" target="_blank"><i
                                    class="fa fa-whatsapp"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="footer-widget">
                        <h5>Mi cuenta </h5>
                        <ul>
                            <li><a href="{% url 'core:home' %}">Inicio</a></li>
                            <li><a href="{% url 'core:list-product' %}">Tienda</a></li>
                            <li><a href="{% url 'core:about-us' %}">Quiénes somos</a></li>
                            <li><a href="{% url 'core:contact' %}">Contáctanos</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 sss ">
                    <div class="newslatter-item ">
                        <div class="">
                            <img src="{% static 'img/webpay1.png' %}" alt="">
                        </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="copyright-reserved">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="copyright-text">
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            Copyright &copy;
                            <script>document.write(new Date().getFullYear());</script> All rights reserved | This
                            template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a
                                href="https://colorlib.com" target="_blank">Colorlib</a>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </div>
                        <div class="payment-pic">
                            <img src="{% static 'img/payment-method.png' %}" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->

    <!-- Js Plugins -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script src="{% static 'js/jquery.countdown.min.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'js/jquery.zoom.min.js' %}"></script>
    <script src="{% static 'js/jQuery.paginate.js' %}"></script>
    <script src="{% static 'js/jquery.dd.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/urls.js' %}"></script>
</body>

</html>

templates/email_content.html
<p> Usted ha recibido un mensaje de un usuario</p>

<dl>
    <dt>Nombre</dt>
    <dd>{{name}}</dd>

    <dt>Email</dt>
    <dd>{{email}}</dd>
    
    <dt>Mensaje</dt>
    <dd>{{message}}</dd>
</dl>

templates/prueba.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Bienvenido a llona
{% endblock %}
{% load static%}
{% block content %}
    <div class="breacrumb-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb-text">
                        <a href="#"><i class="fa fa-home"></i> Inicio</a>
                        <a href="#"><i class="fa fa-home"></i> Tienda</a>
                        <a href="#"><i class="fa fa-home"></i> Finalizar Compra</a>
                        <span>Pagar</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>
    <div class="container">
        <div class="text-center">
            <br>
            <form action="{{response.url}}" method="POST" class="form-group">
                {% csrf_token %}
                <input type="hidden" name="token_ws" value="{{response.token}}">
                <button type="submit" class="btn btn-primary">Ejecutar pago por Webpay</button>
            </form>
        </div>
    </div>
    <br>
{% endblock %}

templates/shopping-cart.html
{% extends 'base/base.html' %}
{% block title %}
    Tienda Llona
{% endblock %}
{% load static%}
{% block content %}

<div class="breacrumb-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb-text">
                    <a href="{% url 'core:home' %}"><i class="fa fa-home"></i> Inicio</a>
                    <a href="{% url 'core:list-product' %}"><i class="fa fa-home"></i> Tienda</a>
                    <span>Carrito de Compras</span>
                </div>
            </div>
        </div>
    </div>
</div>

    <!-- Shopping Cart Section Begin -->
    <section class="shopping-cart spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="cart-table">
                        <table>
                            <thead>
                                <tr>
                                    <th>Imagen</th>
                                    <th class="p-name">Nombre</th>
                                    <th class="p-name">talla</th>
                                    <th>Precio</th>
                                    <th>Cantidad</th>
                                    <th>Total</th>
                                    <th><i class="ti-close"></i></th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for order_item in carro.items.all %}
                                <tr>
                                    <td class="cart-pic first-row"><img src="{{order_item.item.imagen.url}}" alt="" width="100" height="100"></td>
                                    <td class="cart-title first-row">
                                        <h5>{{order_item.item.title}}</h5>
                                    </td>
                                    <td class="cart-title first-row text-center">
                                        <div class="col-md-7">
                                        <h5>{{order_item.talla|title}}</h5>
                                        <!-- <form method="POST" action="{% url 'core:update-size' %}">
                                            {% csrf_token %}
                                            <select class="form-control" id="newsize">
                                                <option>{{order_item.talla|title}}</option>
                                                {% for item in items %}
                                                    {% if item.slug == order_item.item.slug %}
                                                        {% for talla in item.tallas.all %}
                                                            {% if talla|title == order_item.talla|title %}
                                                            {% else %}
                                                            <option value="{{talla}}" name="talla">{{talla|title}}</option>
                                                            {% endif %}
                                                        {% endfor %}
                                                    {% endif %}
                                                {% endfor %}
                                            </select>
                                            <input type="hidden" name="oldsize" value="{{order_item.talla}}">
                                            <input type="hidden" name="slug" value="{{order_item.item.slug}}">
                                            <button type="submit">enviar</button>
                                        </form> -->
                                    </div>
                                    </td>
                                    <td class="p-price first-row">
                                        {% load humanize %}
                                        {% if order_item.item.discount_price|floatformat:"0"|intcomma %}
                                             ${{ order_item.item.discount_price|floatformat:"0"|intcomma }}
                                             <span style="text-decoration:line-through;">${{ order_item.item.price|floatformat:"0"|intcomma }}</span>   
                                        {% else %}
                                                ${{ order_item.totalItem|floatformat:"0"|intcomma }}
                                        {% endif %}
                                    </td>
                                    <td class="qua-col first-row">
                                        <div class="quantity">
                                            <div class="cantidad">
                                                <a class="dec qtybtn" href="{% url 'core:remove-single-item-from-cart' slug=order_item.item.slug talla=order_item.talla %}">-</a>
                                                    <input type="text" value="{{ order_item.quantity }}" readonly>
                                                <a class="inc qtybtn"  href="{% url 'core:add-to-cart' slug=order_item.item.slug talla=order_item.talla %}">+</a>
                                            </div>
                                        </div>
                                    </td>
                                    {% if order_item.item.discount_price %}
                                        
                                        <td class="total-price first-row">${{ order_item.get_total_item_discount_price|floatformat:"0"|intcomma }}
                                            <br>
                                            (${{ order_item.get_amount_saved|floatformat:"0"|intcomma}}Ahorrados)</td>
                                        {% else %}
                                        <td class="total-price first-row">${{ order_item.get_total_item_price|floatformat:"0"|intcomma }}</td>
                                    {% endif %}
                                    <td class="close-td first-row"><a href="{% url 'core:remove-from-cart' slug=order_item.item.slug talla=order_item.talla  %}"><i class="ti-close"></a></i></td>
                                </tr>
                                {% empty %}
                                <td colspan="6">
                                    <br>
                                    <h2 class="text-black">El carrito de compras está vacío</h2>
                                </td>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div class="row">
                        <div class="col-lg-4">
                            <div class="cart-buttons">
                                <a href="{% url 'core:list-product' %}" class="primary-btn continue-shop">Tienda</a>
                                <a href="{% url 'core:order-sumary' %}" class="primary-btn up-cart">Actualizar Carrito</a>
                            </div>
                        </div>
                        <div class="col-lg-4 offset-lg-4">
                            <div class="proceed-checkout">
                                <ul>
                                    {% if get_amount_saved %}
                                    <li class="subtotal">Ahorrado <span>${{ carro.get_amount_saved}}</span></li>
                                    {% endif %}
                                    <li class="cart-total">Total <span>${{ carro.get_total|floatformat:"0"|intcomma }}</span></li>
                                </ul>
                                <a href="{% url 'core:checkout' %}" class="proceed-btn">Finalizar Compra</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}